# Basic
title: ZZZping's Blog
subtitle: 为国为民，侠之大者
#subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: ZZZping's Blog
#description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://zzzping.github.io"
#http://vno.onevcat.com

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: 知乎, description: 知乎, url: 'https://www.zhihu.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 接着忽悠233
    github: ZZZping
    twitter: ZZZping
    facebook: 王毓
    #知乎: ZZZping
    #gplus: 107108267983477358170
    mail: zzzping1024@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
